navbar:
  blog_title: 卖柠檬雪糕的鱼的博客
  ground_glass:
    enable: true
index:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/7EA12C00-1BB9-4C16-8F65-5A6371B63F09.webp
  banner_img_height: 100
  slogan:
    text: 卖柠檬雪糕的鱼的博客
post:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/73BB9E4B-4CD5-48A1-9C32-81E7844573EC.jpeg
  banner_img_height: 85
  default_index_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/A84CE283-6EDF-41A8-B75F-65F94D4C8DE9.jpeg
archive:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/6B0A12AB-54D8-427A-B98E-8F64207B8C3D.jpeg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/mmexport1602581319886.webp
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/50FCEB46-E146-4F46-A840-45082BC73561.jpeg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://gitee.com/uiureir/hexo_netlify_blog/raw/master/img/IMG_2535.jpeg
  banner_img_height: 80
  subtitle: null
  avatar: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/CCCCC56F-9582-44BC-88B6-BB89D32151E5.jpeg
  name: Uiureir
  intro: Uiureir's blog
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
